### ISSUE TITLE
Mac OS X is an operating system (add it in dependencies)

### ISSUE THREAD

**Issue by ubsan** [ihalila/pancurses#1]

**Comment by ihalila** [comment]
I changed the dependencies to use cfg() targets now that Rust 1.8.0 is stable in 2800f66d7bb201da24dc1a22f3e11d5b8aebd1cd , but I don't have an OS X machine so I don't have a convenient way of testing if this works for OS X or not. Can you verify if that's enough?

**Comment by ubsan** [comment]
You need to do a few things to get it to work, but otherwise, yes.

```bash
brew install homebrew/dupes/ncurses
brew link --force ncurses
export LIBRARY_PATH=/usr/local/opt/ncurses/lib/ # add this to your .bashrc
```

**Comment by ihalila** [comment]
Alright, great. I'll close the issue then.
