### ISSUE TITLE
Using the "paste" button in Windows/PDCurses dumps debug info

### ISSUE THREAD

**Issue by Lokathor** [ihalila/pancurses#13]
Using PDCurses on windows, the `Font` button works without issue, but the `Paste` button prints out a bunch of debug seeming info in addition to pasting.

Clipboard: `);`

Output:
```
D:\dev\curse-test>cargo run
   Compiling curse-test v0.1.0 (file:///D:/dev/curse-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.43 secs
     Running `target\debug\curse-test.exe`
ilen = 2
29 3b Some(Character(')'))
Some(Character(';'))
```

program:

```rust
extern crate pancurses;

use pancurses::{initscr, endwin};

fn main() {
    let window = initscr();
    window.printw("Hello Rust");
    window.refresh();
    let out = window.getch();
    let out2 = window.getch();
    endwin();
    println!("{:?}", out);
    println!("{:?}", out2);
}
```

**Comment by Lokathor** [comment]
Edit: I thought it was crashing the program at first while using the demo in the readme, but then I realized that it was just causing the window.getch() call to complete and then end the program normally.

**Comment by Lokathor** [comment]
To be clear: it still dumps the debug info to the console, despite my initial misunderstanding about the crashing part.

**Comment by ihalila** [comment]
Ah, ok. I'll look into it then.

**Comment by ihalila** [comment]
Turns out that it's PDCurses doing the output, check out lines 67 - 71 in pdckbd.c: https://github.com/Bill-Gray/PDCurses/blob/master/win32a/pdckbd.c#L67

Don't know why it does it, first impression is that it's some left-over debugging code. I recommend opening an issue over in Bill-Gray's PDCurses repo, that fork is maintained and pancurses uses it instead of the "official" one.

**Comment by Lokathor** [comment]
They pushed a new commit that fixes the issue:

https://github.com/Bill-Gray/PDCurses/commit/6dbc1996ef7f2129dbac169467749be321f64fb5

Now `pdcurses-sys` needs to target the new version, and then `pancurses` needs to update to the newer version of `pdcurses-sys`.

**Comment by ihalila** [comment]
Cool, I'll update pdcurses-sys soon and push a new version of pancurses.

**Comment by ihalila** [comment]
v0.11 has an updated dependency on pdcurses-sys, which is also now updated. No more debug info should appear!
