### ISSUE TITLE
Library does not support 'winsch'

### ISSUE THREAD

**Issue by Lokathor** [ihalila/pancurses#15]
The library does not currently support the `winsch` function. This allows you to insert a character into the window specified at the current position, pushing other characters to the right (and possibly pushing the final char off the screen entirely).

Ideally this would be implemented as an `insch` method on the `Window` type, along with the `mvinsch` variant as well.

**Comment by ihalila** [comment]
Added insch and mvinsch to Window in 0.10 that I just released.
