### ISSUE TITLE
Flickering text on Windows

### ISSUE THREAD

**Issue by Lokathor** [ihalila/pancurses#22]
I'm not quite sure if this goes here or with pdcurses-sys, but if you clear the window then fill it with characters the characters within the first 49 cells of the first row will flicker slightly while the rest don't flicker at all.

Minimal example program to reproduce:
```rust
extern crate pancurses;

fn main () {
    let w = pancurses::initscr();
    pancurses::curs_set(0);
    pancurses::noecho();
    let (rows,cols) = w.get_max_yx();
    loop {
        let some_i = w.getch();
        w.clear();
        w.mv(0, 0);
        for _ in 0..rows {
            for _ in 0..cols {
                w.addch('#');
            }
        }
        w.refresh();
    }
}
```

If you just tap any key a few times you'll see it flicker between loops, but only with part of the first row.

**Comment by ihalila** [comment]
For me it flickers fairly rarely, and in random spots, it's not confined to the first 49 cells. Removing the w.clear() call eliminates the flickering.

Calling clear() calls clearok(), which forces the next call to refresh() to redraw the whole screen which I'm pretty sure is the reason for the flickering. Leaving out clear() allows PDCurses to not have to redraw everything.

**Comment by Lokathor** [comment]
That does seem to prevent the issue.

I suppose I'll simply document in my library that you shouldn't use `clear` if you plan to overwrite the cells anyway.
