### ISSUE TITLE
resize_term() not implemented in ncurses-rs

### ISSUE THREAD

**Issue by ihalila** [ihalila/pancurses#25]
resize_term() causes a panic

**Comment by gbear605** [comment]
I've resolved the issue on ncurses-rs's side with [this pull request](https://github.com/jeaye/ncurses-rs/pull/142). Once it gets pushed to crates.io, this can easily be resolved here.

**Comment by ihalila** [comment]
Thanks, I'll keep an eye out for a new version of ncurses-rs

**Comment by facelesspanda** [comment]
https://github.com/jeaye/ncurses-rs/pull/142#issuecomment-354577515

Just got pushed.

**Comment by Fierthraix** [comment]
Added the unix version: https://github.com/ihalila/pancurses/pull/30

**Comment by Fierthraix** [comment]
Can you update the `crates.io` package so that these changes can called in the `Cargo.toml` file without a git version?
Thanks in advance.

**Comment by ihalila** [comment]
Yeah, I'll try and put out a new version this week.
