### ISSUE TITLE
Move to latest `winreg` version

### ISSUE THREAD

**Issue by Lokathor** [ihalila/pancurses#28]
The current version of `pancurses` relies on `winreg` 0.4, which in turn uses the 0.2 series of `winapi`. Recently `winapi` moved to 0.3, which includes many improvements, among which is greatly reduced build times. `winreg` has a new 0.5 version out which uses the new `winapi`, and that should be moved to when possible.

**Comment by Fierthraix** [comment]
Should be fixed with [this](https://github.com/ihalila/pancurses/pull/31)

**Comment by ihalila** [comment]
Merged the pull request, thanks for bringing up the issue.
