### ISSUE TITLE
get_max_x and get_max_y return width and height instead of max x and y

### ISSUE THREAD

**Issue by nmoniz** [ihalila/pancurses#29]
Hello,

I was playing around with pancurses and while trying to write chars on the edges of the window I noticed that the get_max_? methods were returning the width and height instead of max x or y. This can be easily worked around by subtracting 1 but I thought that these names are a bit counter intuitive since **width is not** the same as **max x**.

Should this be renamed? Or maybe should the behaviour be changed?

**Comment by ihalila** [comment]
Both ncurses and PDCurses have getmaxx() and getmaxy() and the pancurses functions just call those, which is where the name and behaviour comes from. I don't think pancurses should deviate from them.

**Comment by nmoniz** [comment]
I see, makes complete sense. I'll close the ticket.
