### ISSUE TITLE
Release current HEAD?

### ISSUE THREAD

**Issue by nabijaczleweli** [ihalila/pancurses#3]
The current `HEAD` has a lot of new features (like `Window::attroff()`) which would be good to have.

**Comment by ihalila** [comment]
I will, just need to check a couple of things before I do. Probably get it
out today/tomorrow.

**Comment by nabijaczleweli** [comment]
:+1:

**Comment by ihalila** [comment]
It's released: https://github.com/ihalila/pancurses/releases/tag/0.4.0

**Comment by nabijaczleweli** [comment]
Dope shit
