### ISSUE TITLE
Numpad keys are listed as Unknown

### ISSUE THREAD

**Issue by hellow554** [ihalila/pancurses#33]
The numpad keys appear as unknown keys. Here is a list in hope of implementing them :)

I am under Windows 10 with pancurses master branch

Numlock On

Key|Code
----|-----
`Enter` | 155
`+`    | 161
`-` |  160
`*` | 159
`/` | 154

Numlock Off

Key|Code
----|-----
Insert (0) | 202
Del (.)  | 158
End (1) | 151
Down (2) | 152
Page Down (3) | 153
Left (4) | 148
Center (5) | 149
Right (6) | 150
Home (7) | 145
Up (8) | 146
Page Up (9) | 147

**Comment by ihalila** [comment]
Numpad keys should appear as you would expect on Windows now with v0.15
