### ISSUE TITLE
Asynchronous stdin

### ISSUE THREAD

**Issue by kpcyrd** [ihalila/pancurses#36]
I'm trying to do something similar to what termion does with [async_stdin][0] in cases where there are other streams that can cause draws, like an irc client. Do you have any pointers how something like this can be done? :)

Thanks!

[0]: https://docs.rs/termion/1.5.1/termion/fn.async_stdin.html

**Comment by ihalila** [comment]
I think the most straight-forward thing would be to just use non-blocking mode with getch(). So just set `nodelay(true)` (https://docs.rs/pancurses/0.15.0/pancurses/struct.Window.html#method.nodelay) and call window.getch() periodically.

**Comment by kpcyrd** [comment]
@ihalila I've solved this by setting a timeout of 100ms for getch :) https://github.com/kpcyrd/syrup-rs
