### ISSUE TITLE
Compile error on windows with feature "win32" enabled

### ISSUE THREAD

**Issue by DaTa-** [ihalila/pancurses#37]
This line fails to compile (`warn!` macro is missing)
https://github.com/ihalila/pancurses/blob/65621d5731927dd7090e1055c7d358dfc7354875/src/windows/mod.rs#L167
duo to incorrect cfg condition
https://github.com/ihalila/pancurses/blob/65621d5731927dd7090e1055c7d358dfc7354875/src/lib.rs#L4

**Comment by ihalila** [comment]
Fixed the error in a9122a5151e5e0ab37f5041308cce43c41219831, there's some test failures I'll take a look at but it should work.

**Comment by ihalila** [comment]
The only tests that fail are some doctests that try to initialize the screen, I assume this is related to the running environment not being suitable for the win32 flavor. I'm gonna let that pass since for actual applications it works just fine.

**Comment by nickolay** [comment]
> The only tests that fail are some doctests that try to initialize the screen

I stumbled on this while trying to figure out if there are known problems with the KeyResize event on win32. While I didn't find the reason KeyResize wasn't working, I found two issues that together probably cause the doctests to fail on win32:

* https://github.com/Bill-Gray/PDCurses/issues/50 which is about this error when stdout is redirected
* https://github.com/rust-lang/rust/issues/26309 about rustdoc capturing stdout and ignoring `cargo test -- --nocapture`

For completeness, the error message is:
> LINES value must be >= 2 and <= 600: got -20132
> initscr(): Unable to create SP
