### ISSUE TITLE
Change str functions to take AsRef<str>

### ISSUE THREAD

**Issue by aghast** [ihalila/pancurses#38]
I'm formatting some of my output with `format!()`, which produces `String` instead of `str`.

I'd like to suggest changing, e.g., `Window.addstr(&self, string:&str)` to be generic, something like `Window.addstr<T: AsRef<str>>(&self, string:T)` instead. This would allow passing either `str` or `String` parameters.

**Comment by ihalila** [comment]
Sounds sensible to me, if you don't send a pull request I'll get around to it soon enough.

**Comment by Lokathor** [comment]
While we're at it, `Window::addstr` allocates a `CString` to store the string and then passes the pointer, but on windows+pdcurses at least that [just calls waddch for each c_char in the string](https://github.com/Bill-Gray/PDCurses/blob/068b93cad31a751879411c94534d810ed2018f91/pdcurses/addstr.c#L67). I'm not sure where a good source for ncurses code is but i suspect they do the same thing.

Could we have the rust-level code call `.chars()` and then call `Window::addch` on each one and eliminate the intermediate allocation?

**Comment by ihalila** [comment]
That too sounds sensible.

I think http://invisible-island.net/ncurses/#downloads is the right place to get ncurses code, in case you feel like taking a look.

**Comment by Lokathor** [comment]
yeah, ncurses does essentially the same as pdcurses in this case:

```c
// ncurses-6.1/ncurses/base/lib_addstr.c
NCURSES_EXPORT(int)
waddnstr(WINDOW *win, const char *astr, int n)
{
    const char *str = astr;
    int code = ERR;

    T((T_CALLED("waddnstr(%p,%s,%d)"), (void *) win, _nc_visbufn(astr, n), n));

    if (win && (str != 0)) {
	TR(TRACE_VIRTPUT | TRACE_ATTRS,
	   ("... current %s", _traceattr(WINDOW_ATTRS(win))));
	code = OK;
	if (n < 0)
	    n = (int) strlen(astr);

	TR(TRACE_VIRTPUT, ("str is not null, length = %d", n));
	while ((n-- > 0) && (*str != '\0')) {
	    NCURSES_CH_T ch;
	    TR(TRACE_VIRTPUT, ("*str = %#o", UChar(*str)));
	    SetChar(ch, UChar(*str++), A_NORMAL);
	    if (_nc_waddch_nosync(win, ch) == ERR) {
		code = ERR;
		break;
	    }
	}
	_nc_synchook(win);
    }
    TR(TRACE_VIRTPUT, ("waddnstr returns %d", code));
    returnCode(code);
}
```

**Comment by aghast** [comment]
It appears the correct trait bound is Into<Vec<u8>>, since that is what CString::new takes. But that won't work with references (`&format!("foo")`).

**Comment by Lokathor** [comment]
@aghast Since you already have a PR setup, can you change it to not use CString at all? Just do each char individually with something like

`for ch in s.chars() { w.addch(ch) }`

**Comment by aghast** [comment]
I'm going to pass on that. The `...str` functions in `ncurses` have access to the `_nc_waddch_nosync` function, which you can see in the code above. This lets them add multiple characters without calling the window synchronization function. Calling `addch` from outside would cause the sync function, which includes a call to `wrefresh`, to be called each time.

**Comment by Lokathor** [comment]
Ah, hmm, I guess we'd need to make a flag for if we're targeting PDCurses or not?

**Comment by ihalila** [comment]
You can define platform specific implementations, depending on the configuration either the unix or windows module gets imported as `platform_specific`. I'll close this issue though since this has been dealt with, open up a new one if you want to continue with removing the allocation.
