### ISSUE TITLE
`pancurses::newterm()` takes pointer of possibly-dropped `CString`

### ISSUE THREAD

**Issue by gyscos** [ihalila/pancurses#41]
https://github.com/ihalila/pancurses/blob/master/src/lib.rs#L318

```rust
        curses::newterm(
            t.map(|x| CString::new(x).unwrap().as_ptr())
                .unwrap_or(std::ptr::null()),
            output,
            input,
        )
```

Here a `CString` is created, a pointer is taken from it, but the `CString` itself is destroyed when `map` returns; so the `Option<*const char>`, if not `None`, contains a pointer to freed memory.

This is actually in a big warning from the std docs:
https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr

**Comment by ihalila** [comment]
Good catch, thanks.

**Comment by gyscos** [comment]
I'm afraid doing `match termType` consumes the option and the CString inside. Maybe `match &termType`? Or matching with `Some(ref s)` - not sure if that one would work.

To check, see if you can print termType afterward, to see if it was dropped or not.

**Comment by gyscos** [comment]
This also shows how much the borrowchecker usually helps, and how much we miss it when we go unsafe ;)
