### ISSUE TITLE
Moving subwindow leaves behind the old windows

### ISSUE THREAD

**Issue by WishCow** [ihalila/pancurses#62]
Sorry if this is a very basic question, this is the first time I'm using ncurses.

When I create a subwindow, and I move it, the window is still visible in its old location, it effectively looks like I have two windows.

```rust
fn main() {
    let window = initscr();
    window.keypad(true);
    noecho();
    curs_set(0);
    window.draw_box(0,0);
    let subwin = window.derwin(10, 10, 5, 5).unwrap();)
    subwin.draw_box(0,0);
    subwin.printw("Hello");
    subwin.mvwin(15, 15);
    window.refresh();
    subwin.refresh();
    window.getch();
}
```

This causes the screen to look like this:
![tmp hjkbp4y1fa](https://user-images.githubusercontent.com/969284/51077269-57808980-16a4-11e9-8c52-9b9c6edf1411.png)

I was expecting the "hello" window to only show up once, is there something I'm missing?

**Comment by ratijas** [comment]
It only draws where you tell it to. It has no notion of "window" in the terms of GUI frameworks like X Window System or window managers like KWin. You are not actually "moving a window", just setting other coordinates to count from when drawing.

About the solution, manual .clear() should do.

**Comment by ratijas** [comment]
As a rule of thumb for pa{n,}curses, it's good to clear your terminal before each iteration of your drawing loop.

This issue should be closed, as this is not a bug.

**Comment by WishCow** [comment]
Okay, that wasn't clear, thanks.
