### ISSUE TITLE
Release and activity

### ISSUE THREAD

**Issue by TimonPost** [ihalila/pancurses#74]
Hi there,

I've been working on a library that uses pancurses. Tough I had some complications with some features that it was still lacking. When I checked out the pull requests there were some valuable ones that can be very useful and fixed my problems if they were merged and released. 

The activity of this library is very low. Is there any plan to do a new release and work trough the pull requests? If not I am afraid I have to work around this problem by forking this library and releasing it to get the features that I need.

**Comment by ihalila** [comment]
Hi,

I have very limited time to work on pancurses right now. I haven't abandoned it but the speed of updating won't be improving any time soon.
