### ISSUE TITLE
Get and set XY position of cursor (not mouse) 

### ISSUE THREAD

**Issue by jeanlucthumm** [ihalila/pancurses#79]
Is this possible with pancurses? I looked through all the functions and couldn't find anything.

**Comment by bracketttc** [comment]
The Window type contains `get_cur_x`, `get_cur_y`, and `get_cur_yx` functions to get the current cursor position. It also contains the `mv` function to move the cursor to an argument position.
[ref](https://docs.rs/pancurses/latest/pancurses/struct.Window.html)
